data:
  env_type: "acc"
  env:
    path: "../CTD3/project/env-TD3_risk-rnd-acc-20230322/trajectory/trajectory.csv"
  policy:
    path: "../CTD3/project/policy-TD3_risk-acc-20230322/trajectory/policy_trajectory.csv"

cluster:
  type: "birch"
  threshold: 0.1

  K: 45

action:
  granularity:
    acc: 0.01
    steer: 0.01
