data:
  env_type: "intersection"
  env:
    path: "../CTD3/project/env-TD3_risk-rnd-intersection-20232329/trajectory/trajectory.csv"
  policy:
    path: "../CTD3/project/policy-TD3_risk-intersection-20230329/trajectory/policy_trajectory.csv"

cluster:
  type: "birch"
  threshold: 0.1

  K: 31

action:
  granularity:
    acc: 0.01
    steer: 0.01

property:
  name: ['episode_reward', 'is_crash', 'is_outoflane', 'is_reachdest']
  class: ['base.EpisodeRewardProperty', 'base.OppositeProperty', 'base.OppositeProperty', 'base.OppositeProperty']