data:
  env_type: "intersection"
  env:
    path: "../CTD3/project/policy-TD3_risk-intersection-20230329/trajectory/trajectory.csv"
  policy:
    path: "../CTD3/project/policy-TD3_risk-intersection-20230329/trajectory/policy_trajectory.csv"
  state_ranges: [[1, 7]]
  action_ranges: [[7, 9]]
  reward_ranges: [[9, 10]]
  property_ranges: [[11, 14]]


cluster:
  type: "birch"
  threshold: 0.1

  K: 34

action:
  granularity:
    acc: 0.01
    steer: 0.01

property:
  name: ['episode_reward', 'is_crash', 'is_outoflane', 'is_reachdest']
  class: ['base.EpisodeRewardProperty', 'base.Property', 'base.Property', 'base.Property']