data:
  env_type: "lane_keeping"
  env:
    path: "../CTD3/project/env-TD3_risk-rnd-lane_keeping-20230404/trajectory/trajectory.csv"
  policy:
    path: "../CTD3/project/policy-TD3_risk-lane_keeping-20230318/trajectory/policy_trajectory.csv"
  state_ranges: [ [ 0, 5 ] ]
  action_ranges: [ [ 6, 7 ] ]
  reward_ranges: [ [ 7, 8 ] ]
  property_ranges: [ [ 10, 11 ] ]

cluster:
  type: "birch"
  threshold: 0.5

  K: 3

action:
  granularity:
    acc: 0.01
    steer: 0.01

property:
  name: ['episode_reward', 'is_outoflane']
  class: ['base.EpisodeRewardProperty', 'base.Property']
