data:
  env_type: "lane_keeping"
  env:
    path: "../CTD3/project/policy-TD3_risk-lane_keeping-20230318/trajectory/trajectory.csv"
  policy:
    path: "../CTD3/project/policy-TD3_risk-lane_keeping-20230318/trajectory/policy_trajectory.csv"

cluster:
  type: "birch"
  threshold: 0.1

  K: 6

action:
  granularity:
    acc: 0.01
    steer: 0.01

property:
  name: ['episode_reward', 'is_outoflane']
  class: ['base.EpisodeRewardProperty', 'base.Property']
